[colors.primary]
background = "#191919"
foreground = "#c5c5c5"

[colors.cursor]
text = "#191919"
cursor = "#c5c5c5"

[colors.vi_mode_cursor]
text = "#191919"
cursor = "#c5c5c5"

[colors.search.matches]
foreground = "#191919"
background = "#c5c5c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#525252"
background = "#8c8c8c"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#191919"
red = "#3a3632"
green = "#582c1e"
yellow = "#423f39"
blue = "#50473c"
magenta = "#634723"
cyan = "#5a5149"
white = "#8c8c8c"

[colors.bright]
black = "#525252"
red = "#4e4843"
green = "#763b28"
yellow = "#59554c"
blue = "#6b5f51"
magenta = "#855f2f"
cyan = "#796d62"
white = "#c5c5c5"

[colors.dim]
black = "#c5c5c5"
red = "#4e4843"
green = "#855f2f"
yellow = "#59554c"
blue = "#6b5f51"
magenta = "#763b28"
cyan = "#796d62"
white = "#525252"

